pub mod serial;
pub mod loggers;
pub mod interrupts;
pub mod idt;
pub mod pic;
pub mod timer;
pub mod interrupts_asm;
pub mod keyboard;
// pub mod allocator;
pub mod paging_allocator;
pub mod syscall;
pub mod syscall_handler;
